### ISSUE TITLE
Lack of guidance on Proxy contracts in the Transaction Builder

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-pm#63]
# Part 1: Define the problem

## What problem are you trying to solve?
Currently many smart contracts use a proxy pattern in order to allow upgradability while keeping the same ethereum address. The transaction builder is not able to detect when a smart contract is a proxy and then suggest to load the proper implementation ABI, as is the case of the Safe contract itself.

## What is your hypothesis?
For most of the cases, users would be trying to interact with the implementation contract methods. Detecting that the smart contract is a proxy and giving the user the possibility to load the implementation ABI instead without leaving the app will improve a lot the interaction with many smart contracts.

## What value does this bring to our customer and/or our mission? What is the goal?
Shorting and easing steps at the time of using the transaction builder, as they won't need to use an external service to fill the correct ABI. For cases where a proxy is involved, the automatic ABI resolution is useless.
Some less advanced users are confused about the proxy pattern and they may not be able to get the correct ABI to interact as expected, because they don't know how to get it from external services. Driving them through this process will also improve their experience.

## How do we measure it?
- We can check the number of proxy contracts that the TX-Builder interacts with.

## Links:
https://github.com/safe-global/safe-react-apps/issues/325
https://www.figma.com/file/G7snLqBXWNPANcOj5MhiR7/Transaction-Builder?node-id=1704%3A9019

From this dune query we can get 2 values, only filtering TXs from 2022:

- Number of safes that interact with proxy contracts
- Number of TXs triggered to a proxy contracts
Could happend that not all this TXs belong to the TX-Builder

https://dune.com/queries/697432
  

# Part 2: Shaping the problem 
## Problem Owner

  // Who is responsible for leading the shaping process of this problem statement. Owner should be assigned directly after the Great Filter meeting. PM will assist. 

## Non Goal(s)
  
- Support custom proxy implementations. We will only try to cover standards.
- Show name for known smart contracts. Future iterations could consider to improve this.

### Solution 1  
**Overview**
The proposed solution will involve detecting when a contract is a proxy and allowing the user to load implementation ABI instead. User would be able to see a message when we detect a proxy pattern with the suggested implementation address. We will provide a link to a block explorer so they can validate that the detected ABI is the one they would expect to load.
User would still be able to restore the previous ABI if necessary.
  
**Rough Scoping & Timeline**

Scope would be:
 - Detect that smart contract is a proxy and fetch implementation address
 - Show the user a message to double check the detected implementation ABI
 - Swap proxy ABI for implementation ABI. Allow with a check button to go back to the proxy ABI

**Risk(s), Key Trade Offs & Decisions**

**Concept Mocks**
Message for the user
<img width="946" alt="imagen" src="https://user-images.githubusercontent.com/25051234/170731558-6fdba034-e972-43c5-968f-006de87c3e26.png">

**Comment by rmeissner** [comment]
I have a question that might not be immediately relevant: 
Do we have any how often users run into this issue?

**Comment by mmv08** [comment]
RFC for the problem can be found here: https://docs.google.com/document/d/1WGd6ToCTTTgfnQmtjsYX7DCnrszUXJ38c-8oRsAvaL0/edit
