### ISSUE TITLE
No way to claim SAFE tokens on Mobile

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-pm#73]
# Part 1: Define the problem

## What problem are you trying to solve?

People would want to claim a SAFE token when the airdrop will become available. We would like to bring it for mobile Safe users so that people could claim it wherever they are. I suppose it should be a wow moment, too.

## What is your hypothesis?

  // If we <achieve/enable X>, then <user behavior Y changes in this way> leading to positive metrics Z. Include guesses for size of the win on specific metrics, using past launches as a baseline. 

When we provide a way to claim upcoming SAFE tokens to our eligible users on mobile, then we will see increased mobile new users, and some portion of them will stay or come back to the mobile app later. 

## Links:
  
  // Include useful research, such as user tests, competitive analysis, metrics, or surveys.
  
  

# Part 2: Shaping the problem 
  
  // Once the problem statement has passed the Great Filter, work with the team on the problem statement and elaborate on the following points to create more certainty around the problem and possible solutions. Make sure to identify dependencies and invite the necessary stakeholders early into the shaping process. 
  
## Problem Owner

  // Who is responsible for leading the shaping process of this problem statement. Owner should be assigned directly after the Great Filter meeting. PM will assist. 

## Non Goal(s)
  
  // Controlling the scope of solving the problem. 
 
## Solution
  
  // At the end of the process, if possible, leave only the solution here that you want to be considered during the prioritization vote.  Move all other solutions or ideas to **Alternative solutions**. 
  
### Solution 1
  
  // Provided structure is here for guidance and can be altered. 
  
**Overview**
  
**Rough Scoping & Timeline**

  // At a high level, what's included in V1 vs. later versions? How big of a project is this? What's the roll out / testing plan? 

**Risk(s), Key Trade Offs & Decisions**

  // For example, were there any alternatives considered? What are the value, usability, feasability and business risks and how could we address them? 

**Concept Mocks**

**Comment by sche** [comment]
Lets merge with Web issue

**Comment by sche** [comment]
closed in favor of https://github.com/safe-global/safe-pm/issues/95
