### ISSUE TITLE
User data shouldn't be shared with 3rd parties without user permission

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-pm#98]
# Part 1: Define the problem

## What problem are you trying to solve?
Currently we are a bit limited at the time of allowing certain features to the user. For example we have some users demanding the possibility of using the address book inside a Safe app, which will make total sense, but in terms of information protection this could be an issue, as we could share information that could uniquely identify an user with third party apps, which could conflict with privacy laws in some countries

## What is your hypothesis?
We know that many apps would do a legit use of this data, and would enrich user experience around the address book. To solve this, it would be more apropiate that the user could select which information is willing to share with each Safe App. That way we could allow the user decide if they are fine with sharing address book or camera use while improving the security restricting this permissions instead of enabling it by default.

## What value does this bring to our customer and/or our mission? What is the goal?
Users that would like to have this advanced functionality could decide to take advantage of it. Other more privacy concerned users can decide to keep as it is and not share this data with third party sites.

## How do we measure it?
We have many users that rely on Safe apps for their operations. Later on we will measure the number of times this features are requested by dApps

## Links:
  - MetaMask is also working on a permission module (this is related to their Snaps prototype):
    - https://docs.metamask.io/guide/rpc-api.html#restricted-methods
  

# Part 2: Shaping the problem  
## Problem Owner

  // Who is responsible for leading the shaping process of this problem statement. Owner should be assigned directly after the Great Filter meeting. PM will assist. 

## Non Goal(s)
  
We will focus in first permission examples (camera and address book). We won't be trying to anticipate other potentially future user permissions
 
### Solution 1  
**Overview**
Currently we had many requests in order to be able to navigate to an specific Safe route, accessing the address book information and also to be able to use the camera for convenience of using WalletConnect from portable devices. We decided that this information can't be shared without user consent.
  
**Rough Scoping & Timeline**

- We want to propose a way to define permission system. The way to go would be to add a section into the manifest as they do [for Android system](https://developer.android.com/reference/android/Manifest.permission)
- Manifest can define a property: `permissions: [address-book, camera]`
- Whenever the user is accessing for the first time to a Safe App that request some permissions a message will be shown to the user. User preferences will be stored locally.
- Once the user selected permission preferences, as first approach we will implement a general section where could manage all granted permissions across different Safe Apps. This will allow the user revoke some permission later.
- Some permissions will enable capabilities at iframe level.
- Some permissions will enable or disable the possibility to fetch information from SDK methods, similarilly as Metamask does with RPC methods in the example above.
- To request user permissions we can use same design template proposed for security recommendations.

**Risk(s), Key Trade Offs & Decisions**

**Concept Mocks**
  
## Open Questions
We still need to check with legal implications of allowing this, even with user consent.
We need to check if apps to request user information would require to provide some kind of legal terms. And if so we should disable permission capabilities for the Safe App from the backend, which will cause a backend dependency.

**Comment by yagopv** [comment]
An idea for this permission system could be to develop something similar to the Android one.

1) safe-apps can expose in the manifest.json (or a new permissions-manifest.json) the predefined list of permissions they can ask for (documented for devs):

```
...
permissions: ['camera', 'address-book']
...
```

2) First time the app is loaded we show a popup with the permissions the safe-app ask for. User should accept or decline each one (checkboxes)

3) We save the info (web storage or db) and avoid to show the popup again until the apps is uninstalled / reinstalled

**Comment by rmeissner** [comment]
Why have a static permissioning system compared to a ad-hoc permission request system (e.g. old Android permission system vs new Android/iOS permission system).

MetaMask is also working on something like this and it might make sense to align with them: https://docs.metamask.io/guide/rpc-api.html#restricted-methods

**Comment by yagopv** [comment]
About using an ad-hoc system, yeah I think we can create it easily through the SDK but there are some permissions that should be added explicitly to the iframe so probably implies a reload and the app will lose state :( 

Perhaps we can combine both, camera static vs address-book dynamic for example but we should make further investigation on the current browser APIs (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy#specifications)
